version: "3.8"


services:
  php-fpm:
    container_name: php-fpm
    build:
      context: ./../
      dockerfile: ./docker/php-fpm/Dockerfile
      args:
        - PUID=${PUID}
        - PGID=${PGID}
    volumes:
      - ./../worker-stations/:/var/www/

  nginx:
    container_name: nginx
    build:
      context: ./nginx
    ports:
      - ${NGINX_HOST_HTTP_PORT}:80
    volumes:
      - ../worker-stations:/var/www:rw
    depends_on:
      - php-fpm
    links:
      - php-fpm


  postgres:
      container_name: postgres
      image: postgres:16-alpine3.18
      environment:
          POSTGRES_USER: ${POSTGRES_USER}
          POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
          POSTGRES_DB: ${POSTGRES_DB}
      volumes:
        - ../db_data:/var/lib/postgresql/data
      ports:
        - "5433:5432"
      links:
        - "php-fpm"
      